### ISSUE TITLE
Add possibility to set smartling.client_lib_id directive value and send it to Smartling

### ISSUE THREAD

**Issue by dimitrystd** [Smartling/api-sdk-python#11]
**DoD**:
- Add the new property `clientUid` to SDK
- New property is optional and must have default value
  - Default value must contain name of lib + version
  - Exact format of strings `{"client":"smartling-api-sdk-python","version":"1.0.0" }`
- SDK must add `smartling.client_lib_id` directive to all Upload request into request **params** (not a file body)

Example of implementation in [java sdk](https://github.com/Smartling/api-sdk-java/commit/dbd1219f8e09855fdb1d7f49f6528234fa157165)

**Comment by anatolija** [comment]
Added in v 2.2.1
