### ISSUE TITLE
Push v2.2.3 to pypi

### ISSUE THREAD

**Issue by dflems** [Smartling/api-sdk-python#20]
Looks like there was a recent change that might fix an error we're seeing occasionally: https://github.com/Smartling/api-sdk-python/commit/f82d65685ff332e93934a3e5467b68d8532375be

That change bumped the version from `2.2.2` to `2.2.3` but the new version hasn't been published to [pypi](https://pypi.org/project/SmartlingApiSdk/) where the latest version is `2.2.2`.

@anatolija @junky

**Comment by anatolija** [comment]
Thanks for spotting this issue.
Updated pypi to 2.2.3
