### ISSUE TITLE
Publish an OpenAPI/Swagger spec

### ISSUE THREAD

**Issue by reececomo** [Smartling/api-sdk-python#49]
Hey there 👋 

Reece here from Internationalization team [@Canva](https://github.com/canva).

Would you be able to publish the API spec in the [Open API 2/3 or Swagger format](https://swagger.io/resources/open-api/) (either YAML/JSON file 👍 ). Presumably you're already using something similar under the hood to generate the Smartling API docs.

That way our team could automatically generate a statically-typed Python client with all the correct properties/attributes 👍 ([in PEP-8 too!](https://github.com/Smartling/api-sdk-python/issues/48))

Cheers,
Reece

**Comment by anatolija** [comment]
Hi, Reece

Smartling has github repo to generate all specifications:
https://github.com/Smartling/api-docs
Up to date generated files are here:
JSON https://api-reference.smartling.com/swagger.json
YAML https://api-reference.smartling.com/swagger.yaml
once some of the API changes - this repo is updated and JSON + YAML specs are rebuilt

Regards,
Anatoly

**Comment by reececomo** [comment]
Thanks Anatoly! 👍
