### ISSUE TITLE
SDK handle token refresh automatically

### ISSUE THREAD

**Issue by reececomo** [Smartling/api-sdk-python#51]
SDK automatically handles initial authentication but does not automatically handle token refresh.

```
[401] AUTHENTICATION_ERROR - invalid_token: Invalid token
```

[docs here](https://help.smartling.com/hc/en-us/articles/1260805176849-Authentication#:~:text=Refreshing%20the%20access%20token&text=Before%20your%20access%20token%20expires,without%20having%20to%20re%2Dauthenticate.&text=You%20can%20continue%20to%20refresh,happens%20after%206%2D24%20hours.)

Should be pretty easy to implement in the SDK and would save us having to fork it.

**Comment by reececomo** [comment]
@b3n shared:

> Looks like they do [have this](https://github.com/Smartling/api-sdk-python/blob/master/smartlingApiSdk/AuthClient.py#L75)

So if it is implemented, it's possible that `timeJitter` is not buffered enough?

```python
self._estimates = EstimatesApi(user_id, user_secret, project_id)
# ...
self._estimates.getJobEstimateReportStatus(report_uid, reportType="COST")
#               ^this endpoint failed
```

**Comment by anatolija** [comment]
@[reececomo](https://github.com/reececomo) token expiration is checked before every api call
if necessary it's auto refreshed.
I'm using this API for extensive API calls and sometimes request time is long under high load.
So when checked - the token is OK, but when it's actually hits API server it's expired already.
I'll increase default refresh interval before token is expired.
Meantime you can set it explicitly:
`self._estimates = EstimatesApi(user_id, user_secret, project_id)`
`self._estimates.authClient.timeJitter = 120`

**Comment by reececomo** [comment]
Thanks for that! It only appears to happen every now and then, just wanted to flag!
