### ISSUE TITLE
SDK does not support Python 3

### ISSUE THREAD

**Issue by dmccombs** [Smartling/api-sdk-python#8]
The SDK currently doesn't support Python 3 - there are a number of things that need to be changed aside from running the '2-to-3' utility on it. We've added support for ourselves, but our patch supports only Python 3 and not Python 2. More work is needed for backwards compatibility but I'll include it here for a starting point.

https://gist.github.com/dmccombs/11289220

**Comment by junky** [comment]
We added support of Python 3 in the latest commits - https://github.com/Smartling/api-sdk-python/commit/4a7770a44d9a2f12163d6f03cdf5b5a6d46d9b6c
